server:
  port: 8061

# mybatis datasource数据源配置
#spring:
#  datasource:
##    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
#    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8\
#      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
#      &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true\
#      &nullCatalogMeansCurrent=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  table:
    auto: create
    #create	系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    #update	系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
    #none 		系统不做任何处理。
    #add		新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
  model:
    #扫描用于创建表的对象的包名，多个包用“,”隔开
    pack: my.dubbo.provider.entity
  database:
    type: mysql


# mybatis-plus配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号隔开隔开
  mapper-locations: classpath:my/dubbo/provider/dao/auto/*.xml,classpath*:my/dubbo/provider/dao/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # true返回map时,当查询数据为空时字段返回为null,false这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# dubbo配置
dubbo:
  application:
    name: dubbo-provider
  registry:
    # 读者请自行更改zookeeper地址
    address: 127.0.0.1:2182
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

# elasticsearch 配置
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      #username: elastic
      #password: 123456